apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-reverse-proxy
spec:
  selector:
    matchLabels:
      app: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverse-proxy
        image: launathiel/microsvc_reverse-proxy:v0.0.3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "150m"