# # apiVersion: networking.istio.io/v1alpha3
# # kind: Gateway
# # metadata:
# #   name: my-gateway
# # spec:
# #   selector:
# #     istio: ingressgateway # use istio default controller
# #   servers:
# #   - port:
# #       number: 80
# #       name: http
# #       protocol: HTTP
# #     hosts:
# #     - "launathiel.com"
# # ---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer
spec:
  hosts:
    - "api.pepago.my.id"
  gateways:
    - pepagomyid-gateway
  http:
  - match:
    - uri:
        regex: /?(.*)
    route:
    - destination:
        host: customer.customer.svc.cluster.local #nama service cluster IP
        port:
          number: 8001
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: products
# spec:
#   hosts:
#     - "api.pepago.my.id"
#   gateways:
#     - pepagomyid-gateway
#   http:
#   - match:
#     - uri:
#         prefix: /api/v1/products/?(.*)
#     route:
#     - destination:
#         host: products.products.svc #nama service cluster IP
#         port:
#           number: 8002
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: shopping
# spec:
#   hosts:
#     - "api.pepago.my.id"
#   gateways:
#     - pepagomyid-gateway
#   http:
#   - match:
#     - uri:
#         prefix: /api/v1/shopping/?(.*)
#     route:
#     - destination:
#         host: shopping.shopping.svc #nama service cluster IP
#         port:
#           number: 8003