apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "launathiel.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: customer
spec:
  hosts:
    - "launathiel.com"
  gateways:
    - my-gateway
  http:
  - match:
    - uri:
        prefix: /customer/?(.*)
    route:
    - destination:
        host: customer.customer.svc #nama service cluster IP
        port:
          number: 8001
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: products
spec:
  hosts:
    - "launathiel.com"
  gateways:
    - my-gateway
  http:
  - match:
    - uri:
        prefix: /products/?(.*)
    route:
    - destination:
        host: products.products.svc #nama service cluster IP
        port:
          number: 8002
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shopping
spec:
  hosts:
    - "launathiel.com"
  gateways:
    - my-gateway
  http:
  - match:
    - uri:
        prefix: /shopping/?(.*)
    route:
    - destination:
        host: shopping.shopping.svc #nama service cluster IP
        port:
          number: 8003