apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-rabbitmqcluster
  namespace: rabbitmq
spec:
  replicas: 3
  persistence:
    storageClassName: standard
    storage: 5Gi
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 1700
      default_user= guest
      default_pass = guest
      default_user_tags.administrator = true
  service:
    type: ClusterIP
