apiVersion: v1
kind: ConfigMap
metadata:
  name: products-config
data:
  APP_SECRET: 'this-is-a-secret'
  # RABBITMQ #
  RABBITMQ_USER: 'guest'
  RABBITMQ_PASSWORD: 'guest'
  EXCHANGE_NAME: 'ONLINE_SHOPPING'
  SHOPPING_BINDING_KEY: 'SHOPPING_SERVICE'
  CUSTOMER_BINDING_KEY: 'CUSTOMER_SERVICE'