#####################
# PRODUCTS SERVCICE #
#####################
apiVersion: v1
kind: Service
metadata:
  name: products
  labels:
    app: products
    service: products
spec:
  ports:
  - port: 8002
    name: http
  selector:
    app: products
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: products
  labels:
    account: products
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-v1
  labels:
    app: products
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
      version: v1
  template:
    metadata:
      labels:
        app: products
        version: v1
    spec:
      serviceAccountName: products
      containers:
      - name: products-service
        image: launathiel/products-service:v0.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        securityContext:
          runAsUser: 1000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "150m"
        env:
        - name: MESSAGE
          value: 'This is Kubernetes Environment!'
        - name: PORT
          value: "8002"
        - name: APP_SECRET
          valueFrom:
            configMapKeyRef:
              name: products-config
              key: APP_SECRET
        ## MONGO DB ENVIRONMENT
        - name: MONGO_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: user
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-credentials
              key: password
        - name: DB_HOST
          value: mongodb-service.products.svc.cluster.local
        - name: DB_NAME
          value: products
        ## RABBITMQ ENVIRONMENT
        - name: RABBITMQ_USER
          valueFrom:
            configMapKeyRef:
              name: products-config
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: products-config
              key: RABBITMQ_PASSWORD
        - name: RABBITMQ_HOST
          value: rabbitmq-headless.rabbitmq.svc.cluster.local
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: products-config
              key: EXCHANGE_NAME
        - name: CUSTOMER_BINDING_KEY
          valueFrom:
            configMapKeyRef:
              name: products-config
              key: CUSTOMER_BINDING_KEY
        - name: SHOPPING_BINDING_KEY
          valueFrom:
            configMapKeyRef:
              name: products-config
              key: SHOPPING_BINDING_KEY
        